### ISSUE TITLE
TimeZone: We do not pass timezone around correctly 

### ISSUE THREAD

**Issue by torkelo** [grafana/scenes#146]
There are a few places where we hard code timezone (SceneQueryRunner, AnnotationQueryRunner) currently. 

The biggest challenge is how to handle different time zones in a scene and propagate timezone changes. 

Does a local panel time range mean it also has local timezone setting? How do we inherit timezone but not time range? what if the panel wants local timezone? 

Some tricky bits to look at here.

**Comment by dprokop** [comment]
Closed with https://github.com/grafana/scenes/pull/167
