### ISSUE TITLE
ScenesAppPage: Variable not being interpolated

### ISSUE THREAD

**Issue by tskarhed** [grafana/scenes#226]
Currently, a variable is not being interpolated in the AppPage title. The workaround I have at the moment is this:

```javascript
const repo = new TextBoxVariable({
    name: 'repository-name',
    value: 'grafana/grafana',
    hide: VariableHide.dontHide,
  });

  repo.addActivationHandler(() => {
    const sub = repo.subscribeToState((newState) => {
      appPage.setState({
        title: `${newState.value} overview`,
      });
    });

    return () => {
      sub.unsubscribe();
    };
  });

  return new SceneApp({
    $variables: new SceneVariableSet({
      variables: [repo],
    }),
    pages: [appPage],
  });
```

**Comment by torkelo** [comment]
not sure if a variable should control the page title. A variable on the app level that are hidden like that what purpose does it have? 

Can you describe a scenario where this would be useful?

**Comment by tskarhed** [comment]
You are probably right. I think in my case using the route parameters will be enough. I will close this. I was thinking I had a query variable with available repos, and you could change between them, but that will be better handled through routing.

**Comment by torkelo** [comment]
yea, so far we have managed to use the route params for Dyanamic page titles. But maybe at some point there will be a good use case for variables inside page title
