### ISSUE TITLE
Add second y-axis to PanelBuilders.timeseries()

### ISSUE THREAD

**Issue by tanayshah23** [grafana/scenes#249]
Hello,

We are working with Scenes to build a functionality to compare metrics. But the range of the metrics can vary a lot. So I was wondering how we can add a second y-axis through PanelBuilders.timeseries()

Thanks for the help!

**Comment by dprokop** [comment]
Depending on requirements you can either configure alternative unit for second series, or you can configure an override for field(s) and set axis placement property to a desired side. 

I don't have access to my computer now, but as soon as I am at my keyboard I can provide you with an example. In the meantime you can try configuring second axis in a regular Grafana dashboard, have a look at the resulting field configuration using Panel Inspect, and apply similar configuration using PanelBuilder in your app.

**Comment by dprokop** [comment]
@tanayshah23. Please find the snipped below for an example of how to add a second y-axis:

```ts
PanelBuilders.timeseries()
  .setTitle('My panel')
  .setUnit('ms') //   // Set unit for all series
  .setOverrides((b) =>
    b.matchFieldsWithName('B-series') // Match fields with exact name
      .overrideCustomFieldConfig('axisPlacement', AxisPlacement.Right) // Set axis placement to right
  )
  .build(),
```

Mind, that the example above is setting axis placement for series matching `B-series` name exactly. If you want some more flexibility you, you may want to use `matchFieldsWithNameByRegex`

**Comment by tanayshah23** [comment]
Hi @dprokop ,

Thanks a lot for the help! This worked perfectly

Is there some documentation available that we can refer to for these properties of PanelBuilders? This [documentation](https://grafana.github.io/scenes/docs/getting-started/) doesn't seem to have these intricate details or a reference to them.
