### ISSUE TITLE
Question on Variables: How to loop over multiple values

### ISSUE THREAD

**Issue by ralequi** [grafana/scenes#255]
Hi,

I'm new to grafana scenes and I've a little question, let's say I have something like this:

```typescript
//[...]
function getMainPanels(id_list: number[] = [0, 1, 2, 3]) {
  return id_list.map(id => getMainPanel(id))
}

//[...]
export function getBasicScene(){
//[...]
  return new EmbeddedScene({
    $timeRange: timeRange,
    $data: queryRunner,
    body: new SceneFlexLayout({
      direction: 'column',
      minHeight: 200,
      children: getMainPanels(),
    }),
//[...]
  });
```

Where `getMainPanel` will return a `SceneFlexItem` with its corresponding `VizPanel`. For now that works great but, how can I pass that `id` into the `SceneQueryRunner` ? 
I suppose I've to create a variable but have no idea on where/how to set it on each iteration etc.

For now the list [0,1,2,3] is obviously static, but will come from a query variable at some point. Don't know if that matters or not.

Thanks for any provided support!
A simple link into a testfile where this is covered might be more than enough! Thank you!

**Comment by torkelo** [comment]
You can use SceneByFrameRepeater to repeat a layout for each series/frame returned by a query (this is A LOT more efficient than repeating a panel + query based on a query variable). As there is only the single query, instead of a query variable query that generates a layout for each panel needs to query data.

**Comment by ralequi** [comment]
Thanks for your reply @torkelo !

I'm checking the demos and see I have much to learn. For example, in https://github.com/grafana/scenes/blob/2e344dd328ddadbfa30f3058bf8caf94b5f4acb7/packages/scenes-app/src/demos/panelRepeater.tsx#L6 I don't know how `SceneByFrameRepeater` knows how many repeats should be done. I suppose it's implicitly set by the query but for a non-main-web developer this absolutely looks like dark magic

Similar happens with the drilldown example: https://github.com/grafana/scenes/blob/2e344dd328ddadbfa30f3058bf8caf94b5f4acb7/packages/scenes-app/src/demos/withDrilldown/panels.tsx#L4 Don't know where the "frame" is defined / what is iterating exactly. (Skipping it is something related with temperature)

Any clues on how repetitions are done would be appreciated, but, in any case, at least I've a point to start with, not just a dead-end.
Thank you!

**Comment by torkelo** [comment]
> I don't know how SceneByFrameRepeater knows how many repeats should be done

Well, it repeats a layout with a graph + stat for each series returned by the query. 

The DataFrame is the data structure returned by queries, you can print it to the console to inspects it's properties
