### ISSUE TITLE
SceneQueryRunner: How to pass a custom query for Influx

### ISSUE THREAD

**Issue by tanayshah23** [grafana/scenes#260]
Hello,

I see that there is some difference in the implementation of the `SceneQueryRunner` for InfluxDB from the documentation provided (Prometheus), like I just found out that passing `expr: <query>` doesn't work, whereas, passing specific values like measurement: <column_name> works and it'll then replace the values in `SELECT mean("value") FROM "<view>"."measurement" WHERE time >= now() - 1m and time <= now() GROUP BY time(100ms) fill(null)`. Can you please provide a way we can pass our SQL-like query from SceneQueryRunner, like how can we implement a query `SHOW TAG VALUES WITH KEY = <string>`? I also tried passing the whole query using `query: <query>` and `q: <query>` which still doesn't work.

Also, if we were to use the current way (passing parameters) for querying, how would we replace other fields like aggregation using min(), max(), etc; group by time(1min,2min) etc; how to add where clauses; etc? Any documentation or any function definition, containing all the possible parameters and their inputs, would be really helpful in this case to use it according to our requirements.

Thanks!

**Comment by torkelo** [comment]
Build the query in dashboards, then open the inspector and to go JSON tab, there you find the query model:

![image](https://github.com/grafana/scenes/assets/10999/56304e49-5cea-45f5-a082-1a93e240f53e)

**Comment by torkelo** [comment]
A raw query would look like this 

```
  {
      "datasource": {
        "uid": "P15396BDD62B2BE29",
        "type": "influxdb"
      },
      "alias": "$tag_hostname",
      "dsType": "influxdb",
      "query": "SELECT mean(\"value\") FROM \"default\".\"logins.count\" WHERE (\"datacenter\" =~ /^$datacenter$/ AND \"hostname\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"hostname\"",
      "refId": "A",
      "resultFormat": "time_series",
      "rawQuery": true
    }
```

**Comment by tanayshah23** [comment]
Thanks @torkelo !
