### ISSUE TITLE
VizPanel: Changing plot type on the go

### ISSUE THREAD

**Issue by tanayshah23** [grafana/scenes#265]
Hello,

I wanted to add a functionality where based on the selected value for chart type, I update the plot (if possible), like changing from timeseries to a table or to a bar chart. I am not sure if this is supported by Scenes yet, but I see that it is already implemented in `Data Sources > Explore`
![image](https://github.com/grafana/scenes/assets/44470385/8a6231d3-3f5e-4ae6-ac67-265ea4dfb56b)

Can you please let me know if this is supported in scenes yet? If yes, then can you give an example of how I can go about implementing it?

I did try implementing this using `addActivationHandler()` and `VizPanel.setState()` functionality, but on `forceRender` I couldn't see the changes on the UI.

Here's the code that I tried:
```
const vizPanel = PanelBuilders.table()
                                .setTitle("My Custom Panel")
                                .setData(queryRunner)
                                .setDisplayMode("transparent")
                                .build();

vizPanel.addActivationHandler(() => {
    const sub = metrics_1.subscribeToState((newState) => {
      console.log(vizPanel.state)
      vizPanel.setState({
        pluginId: "timeseries"
      })
      vizPanel.forceRender();
      console.log(vizPanel.state)
    });
    return () => {
      sub.unsubscribe();
    }
  });
```

Thanks!

PS: In the console, I can see the PluginId changed to `timeseries`

**Comment by torkelo** [comment]
You can change visualization settings using setState (add actions to VizPanel via the actions state prop), think you can't change the visualization plugin right now without also changing the key property (to trigger unmount/remount)

**Comment by tanayshah23** [comment]
I'm sorry, I don't quite understand what you are trying to say. From what I understand, we need to "add actions" and change the key to actually see the changes on the UI, is that correct?

Also, I don't see any action property in the state, can you please elaborate on that and give an example if possible how we can do that? And does `key` have to be in a specific format or any random string would work?

Thanks!

**Comment by torkelo** [comment]
@tanayshah23  VizPanel has a state property named headerActions,  add a radio button group there (size=sm). onChange you can call setAction with any options or fieldConfig change you want to change display settings (enable lines, bars, points, etc)
