### ISSUE TITLE
DOM access of a panel

### ISSUE THREAD

**Issue by ptrkkr** [grafana/scenes#280]
Hi!

Is it currently possible to easily access the DOM of a panel to add, for example, a button?
I was thinking about something like the feature "Create DOM elements" in "Apache ECharts Plugin" (https://volkovlabs.io/plugins/volkovlabs-echarts-panel/instance/#create-dom-elements) 

Thanks!

**Comment by torkelo** [comment]
No, but VizPanel has headerActions prop which allow you to add buttons to the top right of the panel
