### ISSUE TITLE
Confusion with Variables, SceneByFrameRepeater, conditional formatting, and parameter-based graphs

### ISSUE THREAD

**Issue by ptrkkr** [grafana/scenes#281]
Hi!

I will try to explain my problems with an example: 

**Example**
I have the following data:

`Host A: [TIMESERIES_CPU]`,
`Host A: [TIMESERIES_LOAD]`,
`Host B: [TIMESERIES_CPU]`,
`Host B: [TIMESERIES_FAN]`,
...

This means I have key-value pairs where every key is the name of a host, and every value is a performance metric of a host.

Currently, I am building for every performance metric of a host a `SceneQueryRunner` where I query using multiple parameters (e.g., hostname).
This enables me to make conditional filtering and parameter-based graphs based on the hostname and other query parameters I used. 
I have not found any way to retrieve all my results (with host keys) in one query. It seems that only simple key-value pairs (i.e., no lists) are allowed in key-value variables. 

**Questions**
* How can I correctly retrieve my data into one query to use `SceneByFrameRepeater` as https://github.com/grafana/scenes/issues/255 states the performance would be much better? Or is there another way to handle my use case efficiently? 
* Based on the first question: How can I achieve conditional formatting? 
* Based on the first question: How can I create parameter-based graphs? For example, every CPU time series has its graph template, and every LOAD time series has its own. 

P.S.: I have already tried to use chained variables, but this does not work as not every host has the same metrics. This resulted in many empty panels. 

Thanks!

**Comment by torkelo** [comment]
Variables support multiple values (arrays of values), same way a normal dashboard does. You have to enable multi value mode (via isMulti). 

 > How can I correctly retrieve my data into one query to use SceneByFrameRepeater 

Just query all your host CPU metrics in one query, all your fan metrics in another. Then use the SceneByFrameRepeater to repeat a layout for each host returned by the queries. Then in the layout you can use SceneDataTransformer to filter data so only the CPU VizPanel get's the cpu data etc. 

> Based on the first question: How can I achieve conditional formatting?

You have to be more specific, what is the condition based on (query result, variable state?, user action?) and what should be the result (formatting), should it impact layout? visualization settings? You need to be more specific. 

> Based on the first question: How can I create parameter-based graphs? For example, every CPU time series has its graph template, and every LOAD time series has its own.

Sure, just create a simple utility function that takes as arguments the different options (template arguments) you need and have it return the corresponding VizPanel

**Comment by ptrkkr** [comment]
> You have to be more specific, what is the condition based on (query result, variable state?, user action?) and what should be the result (formatting), should it impact layout? visualization settings? You need to be more specific.

You have actually already answered my question with the other answers... thanks!

I will try to implement this and come back if I encounter any other problems
Thanks!
