### ISSUE TITLE
Chained variables 

### ISSUE THREAD

**Issue by ptrkkr** [grafana/scenes#283]
Hi!

I want to use chained variables with Postgres as datasource and have tried it like this:

```typescript
const host_name = new QueryVariable({
    name: 'host_name',
    label: 'Host',
    datasource: MY_DATASOURCE,
    query: "SELECT name from host ",
    sort: 1,
    isMulti: false
});
``` 

```typescript
const host_type = new QueryVariable({
    name: 'host_type',
    label: 'Host Type',
    datasource: MY_DATASOURCE,
    query: "SELECT host_type FROM host where name = $host_name ",
});
```

```typescript
const getScene = () => {
    return new EmbeddedScene({
        $variables: new SceneVariableSet({
            variables: [
                host_name,
                host_type
            ],
        }),
        body: new SceneGridLayout({
            children: [getMyTextPanel()],
        }),
        controls: [new VariableValueSelectors({})],
    })
}
```

But `$host_type` returns no value if I use `$host_name` in the query.

Is it even possible because https://grafana.github.io/scenes/docs/variables/ does not mention chained variables at all? 

Thanks!

**Comment by torkelo** [comment]
@ptrkkr is should work, we have many tests (both unit and demos) that have chained variables. 

Should the query not have quotes (if it's a string)? like `SELECT host_type FROM host where name = '$host_name'`

**Comment by torkelo** [comment]
@ptrkkr let me know if that does not work and I will re-open, but pretty sure that should fix it

**Comment by ptrkkr** [comment]
Thx @torkelo, but I have tried it in many different ways, and `SELECT product_type FROM host where name = '$host_name'` was one of them. 
I have also tried it with multi-value instead with `SELECT product_type FROM host where name IN (${host_name})`

Nothing worked until now. Is there something else I could be missing?

P.S.: When I output the resulting query of `SELECT product_type FROM host where name = '$host_name'` to a textbox, it results in a valid SQL query

**Comment by ptrkkr** [comment]
> @ptrkkr it should work, we have many tests (both unit and demos) that have chained variables.

I cannot find these demos with chained variables. If they are available, could you please send me a link to them?

**Comment by torkelo** [comment]
@ptrkkr when you check the network tab and the queries being issued what do you see?

**Comment by ptrkkr** [comment]
@torkelo all of them seem to be successful, but host_type seems not to return anything and `$host_name` is not parsed to any value

![image](https://github.com/grafana/scenes/assets/44293756/91123148-c59b-4416-b80a-c5ee48194c0a)

**Comment by ptrkkr** [comment]
This is the payload

```
{
  "from": "1692173508840",
  "to": "1692195108840",
  "queries": [
    {
      "refId": "host_type",
      "datasource": {
        "type": "postgres",
        "uid": "PD05C8A384E87CB15"
      },
      "rawSql": "SELECT host_type FROM host where name = '$host_name'",
      "format": "table"
    }
  ]
}
```

**Comment by torkelo** [comment]
@ptrkkr try `${host_name}`, not sure underscore is allowed with that variable syntax

**Comment by ptrkkr** [comment]
@torkelo does not work for sorry

**Comment by torkelo** [comment]
@ptrkkr no worries, I am able to replicate it now. investigating what it can be

**Comment by torkelo** [comment]
@ptrkkr sadly this required a fix in the main Grafana project https://github.com/grafana/grafana/pull/73333

**Comment by ptrkkr** [comment]
Alright, thx for the fast fix!
