### ISSUE TITLE
Re-using regular dashboards and panels in Scenes

### ISSUE THREAD

**Issue by smdasoptim** [grafana/scenes#305]
Hello,

I am currently trying out the new Scenes Framework and so far everything works well. It's easy to migrate some of the regular panels into  the Scenes app. But now I've read that it is possible to load existing core dashboards and panels in a scenes app. I could not figure out how though. Is there any reference or explanation available?

Thanks and best regards

**Comment by dprokop** [comment]
@smdasoptim thanks for opening the issue. We do not provide an API for that in the scenes library at the moment. It's available in Grafana core, where we are working on bringing scenes to Grafana dashboards. Here's the implementation: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard-scene/serialization/transformSaveModelToScene.ts


We might want to consider having a utility for this in scenes library, but no immediate plans to do that now.
