### ISSUE TITLE
Define custom event (click)

### ISSUE THREAD

**Issue by korinekgergely** [grafana/scenes#425]
Is it possible to define a unique event (click) for a chart segment?
It is also fine if the same can be done for a label. For example: pie chart. 
Thx in advance.

**Comment by dprokop** [comment]
You can achieve custom click behavior using [Grafana's data links](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/#configure-data-links). 

When [configuring your chart](https://grafana.com/developers/scenes/visualizations#standard-grafana-visualizations) you can use `setLinks` that enables data links config.
