### ISSUE TITLE
[BUG] - Date picker in Observability is switching to UTC when changing the date, instead of keeping the selected time zone

### ISSUE THREAD

**Issue by marinnedea** [grafana/scenes#457]
Under Observability I can set to Sweden UTC+1
![image](https://github.com/grafana/scenes/assets/7581631/388bec86-1328-4925-8c26-001d6ca0c513)
![image](https://github.com/grafana/scenes/assets/7581631/0837abd2-5be1-422a-9dd4-22d02c5b74a0)

But when I try changing to Nov 2
![image](https://github.com/grafana/scenes/assets/7581631/e2066add-468d-48eb-9da7-ad4d27ac363b)

it changes the timezone back to UTC
![image](https://github.com/grafana/scenes/assets/7581631/6f0a9ca5-5c27-42c9-b997-6e7a9de85035)

**Comment by dprokop** [comment]
@domasx2  - this should be fixed with https://github.com/grafana/scenes/pull/420 - is App Observability on the latest scenes?

**Comment by marinnedea** [comment]
@domasx2 tested this in Grafana Play: https://play.grafana.org/a/grafana-k8s-app/navigation/cluster?promName=grafanacloud-play-prom&from=2023-10-31T21:00:00.000Z&to=2023-11-01T20:59:59.000Z - I guess this one is not up to date. 

I'm not able to replicate on my own instance ( Grafana v10.3.0-63317 (e9e7e0b628bb7ac5f657c630375279b7df30826f)

**Comment by domasx2** [comment]
App o11y is on `1.19.0`. Haven't updated yet, currently on freeze for ObsCon.  But this is k8s app :)

**Comment by marinnedea** [comment]
Closing this as it is definitely fixed in 10.3.x . Thank you!
