### ISSUE TITLE
SceneFlexItem: ability to add custom CSS

### ISSUE THREAD

**Issue by kamalmustafayev** [grafana/scenes#480]
I've been using Grafana Scenes and it is great! Thank you for the product! 

I have a question related to `SceneFlexItem`. I see that it implements `SceneFlexItemPlacement` interface that has several CSSProperties such as height, width, direction, etc. Is there any way to add custom CSS properties such as backroundColor, borderRadius, etc?

**Comment by 4bdulla** [comment]
I was wondering about the same question.

**Comment by MahammadAgayev** [comment]
Would be very nice to have!

**Comment by torkelo** [comment]
If you need custom styling, can't you add that to the body scene object react component ?

**Comment by kamalmustafayev** [comment]
Could you give us example for the following snippet? I want to add custom CSS such as background color to SceneFlexLayout

`let layout = new SceneFlexLayout({
    direction: 'column',
    children: [
      new SceneFlexItem({
        body: PanelBuilders.stat().setOption('textMode', BigValueTextMode.Value).build(),
        $data: myQueryRunner1
      }),
      new SceneFlexItem({
        body: PanelBuilders.stat().setOption('textMode', BigValueTextMode.Value).build(),
        $data: myQueryRunner2
      })
    ]
  })`

**Comment by torkelo** [comment]
you would have to wrap SceneFlexLayout in a custom scene object (and Component) that wraps it in a div with background color

**Comment by kamalmustafayev** [comment]
Thank you!
