### ISSUE TITLE
QueryVariable not working with RuntimeDataSource

### ISSUE THREAD

**Issue by academo** [grafana/scenes#497]
error:

When trying to use QueryVariable with RuntimeDataSource an error occurs: `SceneVariableSet updateAndValidate error Error: Couldn't create a query runner for datasource [datasource name]`

Expected behaviour:

Custom (runtime) datasource should be compatible with variables. e.g: by providing the means to implement variable support or a default variable support similar to how plugin datasources implement it

How to reproduce?:

Follow the steps here https://grafana.com/developers/scenes/variables but use a RuntimeDataSource as datasource.

**Comment by torkelo** [comment]
@academo i assume you mean QueryVariable and not SceneQueryRunner ?

**Comment by academo** [comment]
@torkelo maybe?

 the code that creates the error is this one with a runtime datasource:

```const handlers = new QueryVariable({
  name: 'handler',
  datasource: {
    type: 'prometheus',
    uid: '<PROVIDE_GRAFANA_DS_UID>',
  },
  query: {
    query: 'label_values(prometheus_http_requests_total,handler)',
  },
});```

**Comment by torkelo** [comment]
@academo just tested QueryVarable with a runtime data source and it is working, QueryVariable is using the same getDataSource function that SceneQueryRunner is using (which checks the runtime registered data sources). 

https://github.com/grafana/scenes/pull/613 

Make sure your runtime data source implements variable support (via metricFindQuery or the variables property on DataSourceAPI
