### ISSUE TITLE
Variables: picker transitivity issue

### ISSUE THREAD

**Issue by elise-baturone** [grafana/scenes#500]
There is an issue with variables that depend on other variables. It updates accordingly in the second but not third level.
For example: I have a continent, a country, and a city variable. My country query uses the $continent variable and my city query uses the $country variable.
At loading time, the variables have no problem starting out correctly. However, if I change the continent, the country will update to one in that continent as expected, but the city will not change at all, resulting in obviously wrong data that breaks everything.
Example: starting with Europe-France-Paris. changing Europe to Asia and getting Asia-India-Paris.
I have to manually remove the city variable value from the url and reload so it updates accordingly.

Reproduction repo: https://github.com/elise-baturone/scenes-reproduction.git

```[tasklist]
### Tasks
```

**Comment by torkelo** [comment]
can replicate, investigating why / fixing...
