### ISSUE TITLE
Variables: url_params not always valued

### ISSUE THREAD

**Issue by elise-baturone** [grafana/scenes#503]
The global variable `${__url.params}` is not always being valued. Many times, instead of being replaced by it's value with for example the variable picker's values, the url literally has "$%7B__url.params%7D". 
It has this behaviour for activation handlers when using `window.open()` or for a panel menu as you can see here:
```
return new VizPanelMenu({
        items: [
            {
                text: 'Drilldown',
                shortcut: 'D',
                href: encodeURI(prefixRoute(drilldown_view) + '/${__url.params}'),
                // actual (and incorrect) url: http://localhost:3000/a/my-app/http/$%7B__url.params%7D
            },
        ]
    });
```
I've really tried to see if I'm not missing something but I really can't find any way to make this work so I'm guessing it must be a bug?

**Comment by torkelo** [comment]
We do not interpolate menu items, to do that you would have add them dynamically when the menu is opened (via a behavior) and use sceneGraph.interpolate
