### ISSUE TITLE
$__interval interpolated to empty string for Loki queries

### ISSUE THREAD

**Issue by domasx2** [grafana/scenes#507]
I know root cause is not necessarily with Scenes, but bug happens specifically when using scenes, so gonna open it here.

It seems that `$__interval` gets interpolated to empty string for Loki queries, breaking them.

Traced it down to https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/macros/timeMacros.ts#L100 where `data.state.data?.request` is `undefiend`. It appreas it's not set in time for interpolation?

**Comment by dprokop** [comment]
@domasx2 - similar fix need to be applied to Loki? https://github.com/grafana/grafana/pull/79645
