### ISSUE TITLE
__org and __user macros seem not to work in queries

### ISSUE THREAD

**Issue by ptrkkr** [grafana/scenes#517]
https://github.com/grafana/scenes/pull/449 is a very nice enhancement :ok_hand:  thx for that!
But I can't use it in queries for sorry. I have tried it with `rawsql:` (SQL)  and `expr:` (prometheus). Both are not working with __org and __user macros. 
With __url macro for example it is working.
I am using version `1.28.5` for scenes and nightly for grafana.

Both __user and __org macros are working perfectly fine in the text panel.
Any help or suggestions you can give would be fine.

Thx!

**Comment by torkelo** [comment]
@ptrkkr what data source are you using?

**Comment by ptrkkr** [comment]
@torkelo I am using Mimir and PostgreSQL

**Comment by torkelo** [comment]
@ptrkkr 

I just tested this in a prometheus (mimir) query: 

```ts
 body: PanelBuilders.table()
                    .setTitle('ALERTS')
                    .setData(
                      new SceneQueryRunner({
                        datasource: { uid: 'gdev-prometheus' },
                        queries: [
                          {
                            refId: 'A',
                            expr: 'ALERTS ${__org.name} ${__user.login}',
                            format: 'table',
                            instant: true,
                          },
                        ],
                      })
                    )
                    .build(),
```ts

and those interpolated just fine. 


I also tested this 

```ts
 body: PanelBuilders.table()
                    .setTitle('ALERTS')
                    .setData(
                      new SceneQueryRunner({
                        datasource: { uid: 'PBBCEC2D313BC06C3' },
                        queries: [
                          {
                            refId: 'A',
                            rawSql: 'ALERTS ${__org.name} ${__user.login}',
                          },
                        ],
                      })
                    )
                    .build(),
```

with a postgres data source and that also interpolated correctly

**Comment by ptrkkr** [comment]
Thx @torkelo! I found my mistake!
I wasn't using the grafana nightly (because of caching)... I was using `10.2.0-ubuntu` and it did not work with this version. But with `main-ubuntu (10.3.0-152931)` it works perfectly fine for me.
