### ISSUE TITLE
Cannot set legend to invisible in time series.

### ISSUE THREAD

**Issue by arnekristian58** [grafana/scenes#521]
### I have this code:
![image](https://github.com/grafana/scenes/assets/75922066/ccf220ca-d49d-4801-97ba-f0fb607f17cb)
### but the legend is still visible:
![image](https://github.com/grafana/scenes/assets/75922066/77be59a3-25a5-4dc9-b082-bc9bab959152)

**Comment by torkelo** [comment]
it's  .setOption('legend', { showLegend: false })
