### ISSUE TITLE
Variables and activation handlers

### ISSUE THREAD

**Issue by elise-baturone** [grafana/scenes#535]
I created a "group by" variable that changes the query of my panel depending on it's value. The actual query; it cannot be done with a transformation. I therefore coded an activation handler that modifies the query when the variable changes but I am having an issue for the initialisation of my panel. All I do is check the variable's value and create my panel accordingly but the variable value is null at this time. I tried using behaviours instead but nothing matters if the variable is not set when the panels load. What do you suggest?

**Comment by torkelo** [comment]
@elise-baturone use this 

```ts
 protected _variableDependency: VariableDependencyConfig<QueryRunnerState> = new VariableDependencyConfig(this, {
    variableNames: ['groupby'],
    onVariableUpdatesCompleted: (variables, dependencyChanged) =>
      this.onVariableUpdatesCompleted(variables, dependencyChanged),
  });
```

on activation you can check if a variable is ready with `sceneGraph.hasVariableDependencyInLoadingState(this)` 


however be aware these things will change slightly when I merge https://github.com/grafana/scenes/pull/525 which I might do later today
