### ISSUE TITLE
PieChart colours

### ISSUE THREAD

**Issue by korinekgergely** [grafana/scenes#545]
Thanks for the previous replies, they were very helpful!
Next question: how can I guarantee that each value in a piechart always has the same colour?
For example:
Ok - green
Warning - orange
Critical - red
and so on. 
The stat() works with setThresholds.steps, is it possible that it works in this case? Or is the answer quite different?

Thank you in advance.

**Comment by torkelo** [comment]
use value mapping

**Comment by korinekgergely** [comment]
Nice of you to assume I'm an advanced user like you. But I'm not.
Moreover, I would like to clarify my question: I don't want to color by value, but by label (name). It would help a lot if I could get an example.
`.setMappings([
            {
                type: MappingType.ValueToText,
                options: {
                    0: {
                        color: 'red',
                    },
                    1: {
                        color: 'black',
                    },
                    2: {
                        color: 'green',
                    },
                    3: {
                        color: 'purple',
                    },
                },
            }
        ])`
        For example, the above code works, but it does not color after the labels on the piechart, but after the value. Not exactly what I want.
How should I change it?
![Monosnap Monview App - Apps - Grafana 2024-01-24 18-29-21](https://github.com/grafana/scenes/assets/2194896/deeca2c6-ae66-4ead-bcfe-db2ddd639ef4)

**Comment by torkelo** [comment]
@korinekgergely it depends on what your data structure looks like, are you visualizing separate fields/series or rows?

**Comment by korinekgergely** [comment]
Currently, we are visualizing fields.
![Monosnap Edit panel - pichart-status - Dashboards - Grafana 2024-01-25 09-57-42](https://github.com/grafana/scenes/assets/2194896/075b69d2-5436-4e6b-9dae-ae1a61ea2695)

**Comment by korinekgergely** [comment]
Found a solution:
`.setOverrides((b) =>
            b
                .matchFieldsWithName('OK')
                .overrideColor({
                    fixedColor: 'green',
                    mode: 'fixed'
                })
                .matchFieldsWithName('WARNING')
                .overrideColor({
                    fixedColor: 'dark-red',
                    mode: 'fixed'
                })
                .matchFieldsWithName('CRITICAL')
                .overrideColor({
                    fixedColor: 'orange',
                    mode: 'fixed'
                })
                .matchFieldsWithName('UNKOWN')
                .overrideColor({
                    fixedColor: 'grey',
                    mode: 'fixed'
                })
        )`
