### ISSUE TITLE
Table cell text break

### ISSUE THREAD

**Issue by korinekgergely** [grafana/scenes#552]
Is it possible to break long texts in a table cell into several lines?
![Monosnap Monview App - Apps - Grafana 2024-01-30 12-07-09](https://github.com/grafana/scenes/assets/2194896/12ed6bad-c4fe-4f88-9dd6-c2c59435c7d9)
Thank you.

**Comment by torkelo** [comment]
sadly no, it's not supported in the table visualization  https://github.com/grafana/grafana/issues/25623

**Comment by korinekgergely** [comment]
Thank you.
