### ISSUE TITLE
`QueryVariable` not being properly updated with `setState`

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/scenes#562]
I have a main scene with two tabs:

```
const myAppPage = new SceneAppPage({
        title: 'title',
        url: 'url',
        tabs: [tab1, tab2]
});
```
`tab1` is a configuration page where user can select a default value for `VAR_A`. Note that this is built using a custom scene object with dropdowns. I have a config state that stores the selected default value and it gets stored in the app context and passed down to all my scenes where necessary.

In `tab2` scene I have an actual `QueryVariable` `VAR_C`  and I want this to always show as pre-selected whatever default values were chosen in `tab1` for `VAR_A`

Currently, I am checking if my `configState` has  that default value, then use `setState` to update the variable:

```
if (configState?.defaultVal) {
        VAR_C.setState({ text: configState.defaultVal, value: configState.defaultVal });
}
```

However, no matter what, my variable _always_ shows whatever value I selected last while being in `tab2` instead of showing the default that was selected from `tab1`

I have verified that my `configState` has the values I am expecting, and that the `setState` logic is being hit, but still no change on the actual shown value

**Comment by torkelo** [comment]
QueryVariable has some special logic and validation that needs to happen on value changes, use the function changeValueTo that exists on QueryVariable
