### ISSUE TITLE
support for images in scene nav titles

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/scenes#58]
currently there is no way to include images / logos in the scene title. In some cases, we need to display logo to indicate the page type. ( example below, icon of AKS cluster is the distinguisher )

<img width="846" alt="image" src="https://user-images.githubusercontent.com/153843/225212526-37943f9d-2925-4792-9b09-d9a3302708f9.png">
 
As @torkelo suggested, this can be adding image property to NavModelItem item here https://github.com/grafana/scenes/blob/96f3217930863f74c74289ad790f3a26b9c30117/src/components/SceneApp/SceneApp.tsx#L193-L199

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/scenes/pull/60 

you now have titleImg on SceneAppPage
