### ISSUE TITLE
VizPanel legend onClick doesn't filter series

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/scenes#59]
When I have a timeseries panel in a scene with multiple series, clicking on the legend doesn't filter/highlight the series as we do in regular dashboard. 

In the below example, when clicking `medium3z3` i would like to see only that series instead it does nothing.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/153843/225217601-66b9e3fa-12ed-4b28-bec2-99d826b3db61.png">

**Comment by torkelo** [comment]
ah, good catch! we have to to hook these PanelContext handlers up
