### ISSUE TITLE
Resizing SplitLayout clears Span Filters

### ISSUE THREAD

**Issue by gng0** [grafana/scenes#590]
When using SplitLayout with a trace panel as the secondary property, the span filters get cleared everytime the window/panel is resized. The 'Show matches only' toggle isn't affected, but the inputs for all 4 filters don't maintain their state on resizing.

![image](https://github.com/grafana/scenes/assets/157993762/0ebc2a21-0c90-4cdc-85d3-22c311683d4c)

**Comment by torkelo** [comment]
@gng0 unable to replicate this, we are using this component and have not seen any state loss of components/objects inside. 

The splitter resize is only manipulating the div styles, no scene state, unmount etc are happening. 

You will have to debug this a big or try to create replication demo

**Comment by gng0** [comment]
Hi @torkelo, thank you for checking. 

I've recreated the bug in a test scenes app here - https://github.com/gng0/scenes-app-test

I noticed that resizing the panel calls the clear() method in `grafana/public/app/features/explore/TraceView/components/TracePageHeader/SpanFilters/SpanFilters.tsx` but I wasn't able to debug any further from there. Hope this helps!

![image](https://github.com/grafana/scenes/assets/157993762/4b53195d-754c-4398-9bab-b7e7cd1e21ff)

**Comment by torkelo** [comment]
@gng0 was able to track it down! https://github.com/grafana/scenes/issues/590
