### ISSUE TITLE
Diagram Quantity display in standard format

### ISSUE THREAD

**Issue by korinekgergely** [grafana/scenes#605]
Is there a way to write out the metrics on the Y axis in normal format? Or is there any format control procedure?

![Monosnap Monview App - Apps - Grafana 2024-02-14 17-30-05](https://github.com/grafana/scenes/assets/2194896/ab8a82b1-57f0-4402-8018-b3098e8bfb32)

**Comment by dprokop** [comment]
yes, you can configure decimals and units using grafana field configuration. https://grafana.com/docs/grafana/latest/panels-visualizations/configure-standard-options/

It's descibed in the docs: https://grafana.com/developers/scenes/visualizations#step-5-configure-standard-options
