### ISSUE TITLE
Variables: Missing values in variable picker

### ISSUE THREAD

**Issue by jeromeryu** [grafana/scenes#649]
Hi team!
I'm building a scenes application, and I encountered to some problem which seems an like an bug.

<img width="1139" alt="image" src="https://github.com/grafana/scenes/assets/54859212/5a13deb9-91cd-46be-bb61-032e04c1e86f">

It also can be reproduced in scenes demo in this repository. 
If I select options in the bottom, options on the top are not visualized. It's causing some inconvenience in UX. 

How can I fix my dropdown?

Thanks!

**Comment by dprokop** [comment]
@jeromeryu thanks for reporting this, i can reproduce this indeed, however for me it's only the `A` option that's hidden.

We gonna investigate this and come up with a suggestion.

**Comment by jeromeryu** [comment]
Thanks for your help @dprokop ! Apparently it seems like that PR is not included in `10.4.0`. Looking forward for a new version!
