### ISSUE TITLE
Add custom css to override dashboard setting?

### ISSUE THREAD

**Issue by jeromeryu** [grafana/scenes#678]
Hi team!
Is there any way to add custom css to override existing css codes?
I want to remove title space from my scenesapp so that it has more room.
currently I managed to do something like this
```
export const HomePage = () => {
  const scene = useMemo(() => getScene(), []);
  const css = `
  .root > div > div >.scrollbar-view > div > div:first-child {
    display: none;
  }
  `;

  return (
    <div className="root">
      <style>{css}</style>
      <scene.Component model={scene} />;
    </div>
  );
};
```
but it looks weire and messy.. 
Is there any ways that I can achieve this? 

Thanks

**Comment by torkelo** [comment]
not sure I understand, what title space? do you mean the page title? 

you can change how that is rendered with renderTitle (property on SceneAppPage)

**Comment by jeromeryu** [comment]
I want to delete all the random spaces in `page-header` html component, I've tried `renderTitle` but it still leaves some margin.
