### ISSUE TITLE
Tooltip appear and disappear very quickly (like blink)

### ISSUE THREAD

**Issue by bestov94** [grafana/scenes#803]
With the featuresscenes and dashboardScene enabled, the tooltip on timeseries's panels are blinking.
When these features are disabled, the tooltip are shown and not disappear.

**Comment by torkelo** [comment]
@bestov94 we have no other reports like this, can you describe your scenario? browser version, os, grafana version, scenes version, dashboard setup

**Comment by bestov94** [comment]
Hello.
My browser is Firefox ESR 115.2.0esr 64 bits.
My OS version is Debian GNU/Linux 12 (kernel=6.9.7-1~bpo12+1).
My Grafana version is 11.1.0.
I don't know my scenes version.

My custom directives in grafana.ini :
[server]
protocol = https
domain = XXXXXXX
root_url = https://XXXXXXX/grafana/
enable_gzip = true
cert_file = /etc/grafana/grafana.crt
cert_key = /etc/grafana/grafana.key
[analytics]
check_for_updates = false
check_for_plugin_updates = false
[auth.jwt]
enabled = false
[smtp]
enabled = true
host = XXXXXXXX:25
from_address = grafana@XXXXXXXXXX
[panels]
disable_sanitize_html = true
[plugins]
public_key_retrieval_disabled = true
[plugin.grafana-image-renderer]
rendering_ignore_https_errors = true
[feature_toggles] 
enable = scenes,dashboardScene,featureToggleAdminPage

My dashboard has several panels and the "shared tooltip" option enabled.

**Comment by bestov94** [comment]
Ok.
This phenomenon has disappeared with the version 11.2.

**Comment by bestov94** [comment]
Close
