### ISSUE TITLE
Grafana Monitoring demo app, breadcrumbs missing when clicking tabs

### ISSUE THREAD

**Issue by leslie-canva** [grafana/scenes#826]
Hi there, I was on an older commit and noticed when clicking into a tab the breadcrumb would populate. This is something I would like to keep / use.

<img width="845" alt="Screenshot 2024-07-11 at 11 37 48 AM" src="https://github.com/grafana/scenes/assets/141080429/7684d107-c351-47a1-bff9-a0ab96c64fb3">

However, on the latest commit it seems broken / missing now?

![Screenshot 2024-07-11 at 11 38 35 AM](https://github.com/grafana/scenes/assets/141080429/3238c109-2ac9-47db-9b37-ccb2e2e97725)

Excluding my Grafana version etc as all I'm doing is pulling this repo and running `./scripts/demo.sh`

Thanks :)

**Comment by torkelo** [comment]
@leslie-canva this was changed in core Grafana not scenes, should be fixed by https://github.com/grafana/grafana/pull/89102
