### ISSUE TITLE
 is there a way to combine multiple  SceneDataTransformers?

### ISSUE THREAD

**Issue by LouaiMaayah1** [grafana/scenes#856]
is there a way where multiple SceneDataTransformers can be merged or combined?

## Wanted action
```
 const transformedData1 = new SceneDataTransformer({
    $data: queryRunner1,
    transformations: transformations1,
  });

  const transformedData2= new SceneDataTransformer({
    $data: queryRunner2,
    transformations: transformations2,
  });

  const transformedData3 = new SceneDataTransformer({
    $data: queryRunner3,
    transformations: transformations3,
  });

const combinedData = Combine([transformer1,transformer2,transformer3])
const scene = new EmbeddedScene({
$data: combinedData
})
```
is there anything close to this, where when i access the Panel data and all the series are just stacked on top of each other.

**Comment by dprokop** [comment]
@LouaiMaayah1 - as of now there is no built in way of achieving this. You could implement a custom `SceneDataProvider` to achieve handle the data merging, tho the library does not provide such an object yet.
