### ISSUE TITLE
MSSQL Chained Variables are not interpolated

### ISSUE THREAD

**Issue by NaelDj** [grafana/scenes#863]
Hello!

I found this issue (https://github.com/grafana/scenes/issues/283) but I have the same problem but with MSSSQL. I already updated Grafana to 11.1.0 and Scenes to 5.7.3

This is my setup: 
```tsx
export const getScene = () => {
  const projectNo = new QueryVariable({
    name: 'ProjectNo',
    datasource: mydatasource,
    query: 'SELECT distinct ProjectNo FROM projects'
  });
  
  const WPS = new QueryVariable({
    name: 'WPS',
    datasource: mydatasource,
    query: `SELECT distinct Procedure FROM Procedures WHERE projectno = '$ProjectNo'`
  }); 

  return new EmbeddedScene({
    $variables: new SceneVariableSet({
      variables: [projectNo, WPS],
    }),
    controls: [
      new VariableValueSelectors({}), 
    ],
    body: new SceneFlexLayout({
      children: getMyTextPanel()
    }),
  });
}
```

I get this error when the scene is loaded:

![image](https://github.com/user-attachments/assets/f203e8d6-bf83-47a7-91f8-ce8cd5e9deb0)

This is also my stack trace:

![image](https://github.com/user-attachments/assets/2930e735-29c5-4928-89a0-05d11a6f1ab2)

When there is no chained variable everything works. 
Working together with: @LarsStegman

Thank you in advance!

**Comment by torkelo** [comment]
I think you need to use latest Grafana or latest Scenes v5.7.4

**Comment by NaelDj** [comment]
Yes updated to Grafana 11.1.2 worked, thank you!
