### ISSUE TITLE
More than one Apps in the Apps folder

### ISSUE THREAD

**Issue by korinekgergely** [grafana/scenes#881]
In grafana scenes, I want to create an additional application in the Apps folder.
The applications should be independent, with their own router, their own plugin.json. Is it possible to do this? If yes, how?
Thank you in advance.

![Image](https://github.com/user-attachments/assets/66c7427a-79d3-489a-83dc-b93305255137)
![Image](https://github.com/user-attachments/assets/41df8111-9886-4adf-952b-d5d2c5a474a8)

**Comment by torkelo** [comment]
yes you can have how many you want

**Comment by torkelo** [comment]
just add many plugins to the plugins folder (with different ids)

**Comment by korinekgergely** [comment]
@torkelo 
Thank you for your very quick reply. 
Sorry to ask back, but I need more information, I haven't seen a similar multi-app implemented.
Am I understanding correctly that I need to move all the code I write to the plugins folder?
As shown in the example below:

**MAIN-APP/
├── config/
├── provisioning/
│   └── plugins/
│       ├── apps.yaml
│       ├── app1/
│       │   ├── plugin.json
│       │   ├── components/
│       │   ├── pages/
│       │   └── ...
│       └── app2/
│           ├── plugin.json
│           ├── components/
│           ├── pages/
│           └── ...
├── src/ (common code, if want)
└── ...**

app.yaml
```
apiVersion: 1

apps:
  - type: 'nts-monview-app'
    disabled: false
  - type: 'my-new-app'
    disabled: false
```
IF I have to do it differently, please share some important information with me!
Thank you again.

**Comment by torkelo** [comment]
No i mean, move the Grafana plugins folder. You have managed to install / run one plugin , just add another
