### ISSUE TITLE
Explore metrics: Scenes custom variables does not update variable dependency when setState is called

### ISSUE THREAD

**Issue by bohandley** [grafana/scenes#905]
When calling `setState` to change the value of a `CustomVariable` in scenes, it does not update the variable dependency. 

This is how we are testing updating the trail history in Explore metrics tests. We update the variable and then through variable dependency we update the trail history. This works for AdhocVariables but not CustomVariables.

https://github.com/grafana/grafana/blob/880495b6ffd55a2d1901130d333d3d05752a7ac5/public/app/features/trails/DataTrailsHistory.tsx#L127-L134

**Comment by torkelo** [comment]
Call changeValueTo
